version: "3"

services: 
  app:
    build: .
    volumes: 
      - ~/.ssh/docker:/root/.ssh:ro
    environment: 
      - SSH_REMOTE_BIND_HOST=127.0.0.1
      - SSH_REMOTE_BIND_PORT=80
      - SSH_HOST=192.168.23.22
      - SSH_PORT=17222
      - SSH_USER=sysadmin
    ports: 
      - 8888:8080