version: "3"

services: 
  app:
    image: containerize/toolbox:tunnel
    volumes: 
      - ~/.ssh/docker:/root/.ssh:ro
    environment: 
      - SSH_REMOTE_BIND_HOST=127.0.0.1
      - SSH_REMOTE_BIND_PORT=80
      - SSH_HOST=192.168.23.22
      - SSH_PORT=17222
      - SSH_USER=sysadmin
    ports: 
      - 8888:8080
  test:
    image: containerize/toolbox:tunnel
    volumes: 
      - ~/.ssh/docker:/root/.ssh:ro
    restart: always
    environment: 
      - SSH_REMOTE_BIND_HOST=127.0.0.1
      - SSH_REMOTE_BIND_PORT=80
      - SSH_HOST=192.168.23.100
      - SSH_USER=root
    ports: 
      - 8887:8080